CREATE TABLE IF NOT EXISTS users (
    user_id NUMERIC(19,0) NOT NULL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    birth_date TIMESTAMP(6) NOT NULL
);